---
- name: Installing All my general packages
  apt: update_cache=yes state=latest name={{ item }}
  with_items:
    - vim
    - git
    - net-tools

- name: Adding VS code dependency 
  shell: curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg && mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg && sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list' 
  register: vscode_dependency

- name: Install VS code  
  apt: update_cache=yes state=latest name=code
  when: vscode_dependency.changed

- name: Install Slack
  apt: 
   deb: https://downloads.slack-edge.com/linux_releases/slack-desktop-{{slack_version}}-amd64.deb

