---
- name: Installing necessary tools 
  apt: update_cache=yes state=latest name={{ item }}
  with_items:
    - tmux
    - zsh
    - virtualbox
    - silversearcher-ag
    - httpie
    - httpie

- name: Installing python packages
  pip: 
    name: "{{ item }}"
  with_items:
    - ansible-lint 

- name: Installing tools or package by ruby gem package manager
  gem: 
    name: "{{ item }}"
    state: present
  with_items:
    - terraform_landscape 
